# Generated by Django 2.0 on 2018-12-13 17:20

from django.db import migrations, models
import misc.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultCheckinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('consult_code', models.CharField(blank=True, max_length=64, null=True)),
                ('consult_pmemo', models.TextField(blank=True, null=True)),
                ('consult_pbody', models.TextField(blank=True, null=True)),
                ('check_time', models.DateTimeField(blank=True, default='2018-12-13 17:20:30', null=True)),
                ('check_state', models.IntegerField(blank=True, null=True)),
                ('check_memo', models.TextField(blank=True, null=True)),
                ('checker', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'consult_checkinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultExpert',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('ce_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('expert_code', models.CharField(blank=True, max_length=64, null=True)),
                ('consult_code', models.CharField(blank=True, max_length=64, null=True)),
                ('insert_time', models.DateTimeField(blank=True, default='2018-12-13 17:20:30', null=True)),
                ('creater', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'consult_expert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('consult_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('consulter', models.CharField(blank=True, max_length=64, null=True)),
                ('consult_title', models.CharField(blank=True, max_length=64, null=True)),
                ('consult_memo', models.TextField(blank=True, null=True)),
                ('consult_body', models.TextField(blank=True, null=True)),
                ('consult_time', models.DateTimeField(blank=True, null=True)),
                ('consult_endtime', models.DateTimeField(blank=True, null=True)),
                ('consult_state', models.IntegerField(blank=True, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'consult_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultReplyCheckinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('reply_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
                ('check_state', models.IntegerField(blank=True, null=True)),
                ('check_memo', models.TextField(blank=True, null=True)),
                ('checker', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'consult_reply_checkinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultReplyInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('reply_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True)),
                ('consult_code', models.CharField(blank=True, max_length=64, null=True)),
                ('reply_body', models.TextField(blank=True, null=True)),
                ('reply_state', models.IntegerField(blank=True, null=True)),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consult_reply_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultRrinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('consult_code', models.CharField(blank=True, max_length=64, null=True)),
                ('rrtype', models.IntegerField(blank=True, null=True)),
                ('rrcode', models.CharField(blank=True, max_length=64, null=True)),
                ('rrmain', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consult_rrinfo',
                'managed': False,
            },
        ),
    ]
