# Generated by Django 2.0 on 2018-12-13 17:20

import account.models
from django.db import migrations, models
import misc.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('account_code', models.CharField(default=misc.misc.gen_uuid32, max_length=32, unique=True)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('state', models.IntegerField(default=1)),
                ('dept_code', models.CharField(blank=True, max_length=32, null=True)),
                ('account_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=64, null=True)),
                ('account_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('user_mobile', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('user_email', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'account_info',
                'managed': True,
            },
            managers=[
                ('objects', account.models.AccountInfoManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountDisableFuncinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32)),
                ('func_code', models.CharField(max_length=64)),
                ('state', models.IntegerField(default=1)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_disable_funcinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountRoleInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32)),
                ('role_code', models.CharField(max_length=64)),
                ('state', models.IntegerField(default=1)),
                ('type', models.IntegerField(default=0)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_role_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deptinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('dept_code', models.CharField(default=misc.misc.gen_uuid32, max_length=32, unique=True)),
                ('dept_name', models.CharField(max_length=64, unique=True)),
                ('pdept_code', models.CharField(default='0', max_length=32)),
                ('dept_level', models.IntegerField(default=1)),
                ('dept_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('region_code', models.IntegerField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=64, null=True)),
                ('manager_mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('addr', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.IntegerField(default=1)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deptinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FunctionInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('func_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('func_name', models.CharField(blank=True, max_length=64, null=True)),
                ('func_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('func_url', models.CharField(blank=True, max_length=255, null=True)),
                ('add_param', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.IntegerField(default=0)),
                ('pfunc_code', models.CharField(blank=True, max_length=64, null=True)),
                ('func_order', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=1)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'function_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoleFuncInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=64)),
                ('func_code', models.CharField(max_length=64)),
                ('state', models.IntegerField(default=1)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_func_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('role_name', models.CharField(max_length=64, unique=True)),
                ('role_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(default=1)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_info',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='rolefuncinfo',
            unique_together={('role_code', 'func_code')},
        ),
        migrations.AlterUniqueTogether(
            name='accountroleinfo',
            unique_together={('account', 'role_code', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='accountdisablefuncinfo',
            unique_together={('account', 'func_code')},
        ),
    ]
