# Generated by Django 2.1.1 on 2019-12-12 11:05

from django.db import migrations, models
import misc.misc
import misc.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('activity_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('activity_title', models.CharField(max_length=64, verbose_name='活动标题')),
                ('activity_abstract', models.CharField(max_length=255, verbose_name='活动摘要')),
                ('activity_content', models.TextField(verbose_name='活动内容')),
                ('activity_type', models.IntegerField(verbose_name='活动形式')),
                ('has_lottery', models.IntegerField(blank=True, default=2, null=True, verbose_name='是否有抽奖')),
                ('lottery_desc', models.TextField(blank=True, null=True, verbose_name='抽奖描述')),
                ('activity_sort', models.IntegerField(verbose_name='活动内容分类')),
                ('activity_site', models.URLField(blank=True, max_length=255, null=True, verbose_name='线上活动url')),
                ('district_id', models.IntegerField(blank=True, null=True, verbose_name='活动地区')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动详细地址')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10, max_length=15, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10, max_length=15, verbose_name='纬度')),
                ('online_time', models.DateTimeField(verbose_name='上线时间')),
                ('down_time', models.DateTimeField(verbose_name='下架时间')),
                ('signup_start_time', models.DateTimeField(verbose_name='报名开始时间')),
                ('signup_end_time', models.DateTimeField(verbose_name='报名截止时间')),
                ('activity_start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('activity_end_time', models.DateTimeField(verbose_name='活动结束时间')),
                ('top', models.IntegerField(blank=True, default=2, null=True, verbose_name='是否置顶')),
                ('top_time', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('summary_time', models.DateTimeField(blank=True, null=True, verbose_name='总结时间')),
                ('max_people_number', models.IntegerField(verbose_name='活动最大参与人数')),
                ('signup_check', models.IntegerField(blank=True, default=2, null=True, verbose_name='报名是否需要审核')),
                ('signup_people_number', models.IntegerField(blank=True, null=True, verbose_name='报名人数')),
                ('activity_summary', models.TextField(blank=True, null=True, verbose_name='活动总结')),
                ('reach_intent', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动达成意向')),
                ('contacter', models.CharField(max_length=32, verbose_name='活动联系人')),
                ('mobile', models.CharField(max_length=11, validators=[misc.validate.validate_mobile], verbose_name='手机号码')),
                ('state', models.IntegerField(blank=True, default=1, null=True, verbose_name='活动状态')),
                ('insert_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('comment_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('activity_code', models.CharField(max_length=64, verbose_name='活动标题')),
                ('signup_code', models.CharField(max_length=64, verbose_name='报名编号')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='评论内容')),
                ('state', models.IntegerField(blank=True, default=2, null=True, verbose_name='评论状态')),
                ('insert_time', models.DateTimeField(blank=True, default='2019-12-12 11:05:57', null=True, verbose_name='评论时间')),
            ],
            options={
                'db_table': 'activity_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityGift',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('gift_code', models.CharField(default='Po4ZUMtla6BHWsiCACGXX3bxfk4mJKtJ', max_length=64, unique=True)),
                ('activity_code', models.CharField(max_length=64, verbose_name='活动标题')),
                ('gift_name', models.CharField(max_length=32, verbose_name='活动礼品名称')),
                ('gift_abstract', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动礼品描述')),
                ('state', models.IntegerField(blank=True, default=1, null=True, verbose_name='活动礼品状态')),
                ('insert_time', models.DateTimeField(blank=True, default='2019-12-12 11:05:57', null=True, verbose_name='插入时间')),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'activity_gift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLottery',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('lottery_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('activity_code', models.CharField(max_length=64, verbose_name='活动标题')),
                ('type', models.IntegerField(verbose_name='抽奖形式1线上2线下')),
                ('lottery_title', models.CharField(max_length=50, verbose_name='抽奖标题')),
                ('start_time', models.DateTimeField(verbose_name='抽奖开始时间')),
                ('end_time', models.DateTimeField(verbose_name='抽奖结束时间')),
                ('lottery_num', models.IntegerField(blank=True, default=1, verbose_name='抽奖次数')),
                ('state', models.IntegerField(verbose_name='抽奖状态1正常2禁用')),
                ('insert_time', models.DateTimeField(blank=True, default='2019-12-12 11:05:57', null=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'activity_lottery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityPrize',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('prize_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('lottery_code', models.CharField(max_length=64, verbose_name='抽奖编号')),
                ('prize_name', models.CharField(max_length=64, verbose_name='奖品名称')),
                ('prize_type', models.IntegerField(verbose_name='奖品类型0未中奖(谢谢参与)1一等奖2二等奖3三等奖4四等将')),
                ('probability', models.IntegerField(verbose_name='概率')),
                ('prize_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='奖品描述')),
                ('prize_num', models.IntegerField(verbose_name='奖品数量')),
                ('remain_num', models.IntegerField(blank=True, null=True, verbose_name='剩余未抽中数量')),
                ('state', models.IntegerField(verbose_name='奖品状态1正常2禁用')),
                ('insert_time', models.DateTimeField(blank=True, default='2019-12-12 11:05:57', null=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'activity_prize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityPrizeWinner',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('win_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('activity_code', models.CharField(max_length=64, verbose_name='活动编号')),
                ('lottery_code', models.CharField(max_length=64, verbose_name='抽奖编号')),
                ('prize_code', models.CharField(max_length=64, verbose_name='奖品编号')),
                ('mobile', models.CharField(max_length=64, verbose_name='中奖者手机号')),
                ('win_time', models.DateTimeField(verbose_name='中奖时间')),
                ('account_code', models.CharField(max_length=64, verbose_name='中奖者关联帐号')),
            ],
            options={
                'db_table': 'activity_prize_winner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitySignup',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('signup_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('activity_code', models.CharField(max_length=64, verbose_name='活动标题')),
                ('signup_name', models.CharField(max_length=32, verbose_name='报名者姓名')),
                ('signup_mobile', models.CharField(max_length=11, validators=[misc.validate.validate_mobile], verbose_name='报名者手机')),
                ('verify_code', models.CharField(default=True, max_length=32, null=True, verbose_name='手机短信验证码')),
                ('signup_email', models.CharField(max_length=64, validators=[misc.validate.validate_email], verbose_name='电子邮箱')),
                ('company_info', models.CharField(blank=True, max_length=64, null=True, verbose_name='单位信息')),
                ('concern_content', models.CharField(blank=True, max_length=255, null=True, verbose_name='比较关注的内容')),
                ('account_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='报名者账号')),
                ('change_num', models.IntegerField(blank=True, null=True, verbose_name='信息修改次数')),
                ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('check_state', models.IntegerField(blank=True, default=1, null=True, verbose_name='审核状态')),
                ('insert_time', models.DateTimeField(blank=True, default='2019-12-12 11:05:57', null=True, verbose_name='报名时间')),
            ],
            options={
                'db_table': 'activity_signup',
                'managed': False,
            },
        ),
    ]
