# Generated by Django 2.0 on 2018-12-13 17:20

from django.db import migrations, models
import misc.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGroupInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=64, null=True)),
                ('group_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_group_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(blank=True, max_length=64, null=True)),
                ('news_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64)),
                ('caption', models.CharField(blank=True, max_length=64, null=True)),
                ('caption_ext', models.CharField(blank=True, max_length=64, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('publisher', models.CharField(blank=True, max_length=32, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('uptime', models.DateTimeField(blank=True, db_column='upTime', null=True)),
                ('down_time', models.DateTimeField(blank=True, null=True)),
                ('top_tag', models.IntegerField(blank=True, null=True)),
                ('top_time', models.DateTimeField(blank=True, null=True)),
                ('face_pic', models.CharField(blank=True, max_length=64, null=True)),
                ('newsd_body', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('account_code', models.CharField(blank=True, max_length=32, null=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
                ('check_state', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyGroupInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=64, null=True)),
                ('group_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_group_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(blank=True, max_length=64, null=True)),
                ('policy_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64)),
                ('caption', models.CharField(blank=True, max_length=64, null=True)),
                ('caption_ext', models.CharField(blank=True, max_length=64, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('publisher', models.CharField(blank=True, max_length=64, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('top_tag', models.IntegerField(blank=True, null=True)),
                ('face_pic', models.CharField(blank=True, max_length=64, null=True)),
                ('newsd_body', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'policy_info',
                'managed': False,
            },
        ),
    ]
