# Generated by Django 2.1.1 on 2019-12-12 11:05

from django.db import migrations, models
import misc.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGroupInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('group_name', models.CharField(max_length=64, unique=True, verbose_name='新闻栏目名称')),
                ('group_memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻栏目描述')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻栏目logo')),
                ('state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_group_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=64)),
                ('news_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('caption', models.CharField(max_length=64, verbose_name='新闻主标题')),
                ('caption_ext', models.CharField(max_length=64, verbose_name='新闻副标题')),
                ('author', models.CharField(max_length=32, verbose_name='作者名称')),
                ('publisher', models.CharField(max_length=32, verbose_name='发行单位')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('up_time', models.DateTimeField(verbose_name='上架时间')),
                ('down_time', models.DateTimeField(verbose_name='下架时间')),
                ('top_tag', models.IntegerField(verbose_name='是否置顶')),
                ('top_time', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('face_pic', models.CharField(blank=True, max_length=64, null=True, verbose_name='新闻导引图片')),
                ('news_body', models.TextField(verbose_name='新闻详情')),
                ('state', models.IntegerField(verbose_name='新闻状态')),
                ('creater', models.CharField(blank=True, max_length=32, null=True, verbose_name='新闻创建者')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='新闻创建时间')),
                ('district_id', models.IntegerField(verbose_name='新闻所属地区')),
                ('source', models.IntegerField(verbose_name='新闻来源')),
                ('account_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='审核人')),
                ('check_time', models.DateTimeField(verbose_name='审核时间')),
                ('check_state', models.IntegerField(verbose_name='审核状态')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='点击量')),
            ],
            options={
                'db_table': 'news_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyGroupInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(default='Xgo6ie6k5GD2mkcsl2qk7Suy9j0XPZj4', max_length=64, unique=True)),
                ('group_name', models.CharField(max_length=64, unique=True, verbose_name='政策法规栏目名称')),
                ('group_memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='政策法规栏目描述')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='政策法规栏目logo')),
                ('state', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'policy_group_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=64)),
                ('policy_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64)),
                ('caption', models.CharField(max_length=64, verbose_name='政策法规主标题')),
                ('caption_ext', models.CharField(max_length=64, verbose_name='政策法规副标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者名称')),
                ('publisher', models.CharField(max_length=64, verbose_name='发行单位')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('top_tag', models.IntegerField(blank=True, verbose_name='是否置顶')),
                ('top_time', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('face_pic', models.CharField(blank=True, max_length=64, null=True, verbose_name='政策法规导引图片')),
                ('news_body', models.TextField(verbose_name='政策法规详情')),
                ('state', models.IntegerField(verbose_name='政策法规状态')),
                ('creater', models.CharField(blank=True, max_length=32, null=True, verbose_name='政策法规创建者')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='政策法规创建时间')),
                ('district_id', models.IntegerField(verbose_name='政策法规所属地区')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='政策法规来源')),
            ],
            options={
                'db_table': 'policy_info',
                'managed': False,
            },
        ),
    ]
