# Generated by Django 2.1.1 on 2019-12-12 11:05

from django.db import migrations, models
import misc.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('key_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('key_type', models.IntegerField(blank=True, null=True)),
                ('object_code', models.CharField(max_length=64)),
                ('key_info', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=64, null=True)),
                ('word_vector', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keywords_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequirementsInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('req_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('req_name', models.CharField(blank=True, max_length=64, null=True)),
                ('req_form_type', models.IntegerField(blank=True, null=True)),
                ('r_abstract', models.TextField(blank=True, null=True)),
                ('use_type', models.IntegerField(blank=True, null=True)),
                ('cooperation_type', models.IntegerField(blank=True, null=True)),
                ('obtain_type', models.IntegerField(blank=True, null=True)),
                ('osource_name', models.CharField(blank=True, max_length=64, null=True)),
                ('obtain_source', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_type', models.IntegerField(blank=True, null=True)),
                ('owner_type', models.IntegerField(blank=True, null=True)),
                ('owner_code', models.CharField(blank=True, max_length=64, null=True)),
                ('owner_abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('rcoop_t_abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_dateb', models.DateTimeField(blank=True, null=True)),
                ('expiry_datee', models.DateTimeField(blank=True, null=True)),
                ('original_data', models.CharField(blank=True, max_length=255, null=True)),
                ('show_state', models.IntegerField(blank=True, null=True)),
                ('sniff_state', models.IntegerField(blank=True, null=True)),
                ('sniff_time', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now=True, null=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True)),
                ('r_abstract_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirements_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultsInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('r_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('r_name', models.CharField(blank=True, max_length=64, null=True)),
                ('r_form_type', models.IntegerField(blank=True, null=True)),
                ('r_abstract', models.TextField(blank=True, null=True)),
                ('use_type', models.IntegerField(blank=True, null=True)),
                ('obtain_type', models.IntegerField(blank=True, null=True)),
                ('osource_name', models.CharField(blank=True, max_length=64, null=True)),
                ('obtain_source', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_type', models.IntegerField(blank=True, null=True)),
                ('owner_type', models.IntegerField(blank=True, null=True)),
                ('owner_abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('r_coop_t_abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_dateb', models.DateTimeField(blank=True, null=True)),
                ('expiry_datee', models.DateTimeField(blank=True, null=True)),
                ('rexpiry_dateb', models.DateTimeField(blank=True, null=True)),
                ('rexpiry_datee', models.DateTimeField(blank=True, null=True)),
                ('original_data', models.CharField(blank=True, max_length=255, null=True)),
                ('show_state', models.IntegerField(blank=True, null=True)),
                ('sniff_state', models.IntegerField(blank=True, null=True)),
                ('sniff_time', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now=True, null=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True)),
                ('r_abstract_detail', models.TextField(blank=True, null=True)),
                ('patent_number', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'results_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VectorDifference',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('key1', models.CharField(max_length=255)),
                ('key2', models.CharField(max_length=255)),
                ('vector_difference', models.FloatField(blank=True, null=True)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'vector_difference',
                'managed': False,
            },
        ),
    ]
