# Generated by Django 2.1.1 on 2019-12-12 11:05

from django.db import migrations, models
import misc.misc
import misc.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseBaseinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('ecode', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('ename', models.CharField(max_length=64, verbose_name='企业名称')),
                ('eabbr', models.CharField(max_length=32, verbose_name='企业简称')),
                ('business_license', models.CharField(default=None, max_length=64, unique=True, validators=[misc.validate.validate_license], verbose_name='营业执照')),
                ('eabstract', models.TextField(max_length=500, verbose_name='企业简介')),
                ('homepage', models.URLField(blank=True, max_length=128, null=True, verbose_name='企业官网')),
                ('etel', models.CharField(blank=True, max_length=16, null=True, validators=[misc.validate.validate_tel], verbose_name='企业电话')),
                ('manager', models.CharField(max_length=16, verbose_name='企业联系人')),
                ('emobile', models.CharField(max_length=16, validators=[misc.validate.validate_mobile], verbose_name='企业手机')),
                ('eemail', models.CharField(blank=True, max_length=64, null=True, validators=[misc.validate.validate_email], verbose_name='企业邮箱')),
                ('addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='企业地址')),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True, validators=[misc.validate.validate_zipcode], verbose_name='企业邮编')),
                ('elevel', models.IntegerField(blank=True, default=1, null=True, verbose_name='业务能力评级(1-5)')),
                ('credi_tvalue', models.IntegerField(blank=True, default=0, null=True, verbose_name='企业信用值(0-100)')),
                ('manager_idtype', models.IntegerField(default=1, verbose_name='法人证件类型')),
                ('manager_id', models.CharField(max_length=32, verbose_name='法人证件号码')),
                ('state', models.IntegerField(blank=True, default=2, null=True, verbose_name='状态')),
                ('eabstract_detail', models.TextField(blank=True, max_length=65535, null=True, verbose_name='企业详细')),
                ('creater', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建者')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account_code', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='关联帐号')),
            ],
            options={
                'db_table': 'enterprise_baseinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('pname', models.CharField(max_length=64, verbose_name='个人姓名')),
                ('psex', models.IntegerField(verbose_name='性别')),
                ('pid_type', models.IntegerField(verbose_name='证件类型')),
                ('pid', models.CharField(max_length=32, verbose_name='证件号码')),
                ('pmobile', models.CharField(max_length=11, validators=[misc.validate.validate_mobile], verbose_name='手机号码')),
                ('ptel', models.CharField(blank=True, max_length=16, null=True, validators=[misc.validate.validate_tel], verbose_name='固话')),
                ('pemail', models.CharField(max_length=64, validators=[misc.validate.validate_email], verbose_name='邮箱')),
                ('peducation', models.IntegerField(verbose_name='学历')),
                ('pabstract', models.TextField(max_length=500, verbose_name='简介')),
                ('state', models.IntegerField(blank=True, default=2, null=True, verbose_name='状态')),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='关联帐号')),
            ],
            options={
                'db_table': 'personal_info',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='personalinfo',
            unique_together={('pid_type', 'pid')},
        ),
    ]
