# Generated by Django 2.1.1 on 2019-12-12 11:05

from django.db import migrations, models
import misc.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContacctInformation',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32, validators=[misc.validate.validate_mobile])),
                ('tel', models.CharField(blank=True, max_length=32, null=True, validators=[misc.validate.validate_tel])),
                ('email', models.CharField(blank=True, max_length=32, null=True, validators=[misc.validate.validate_email])),
                ('district_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'contact_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MessageInformation',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('code', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('phone', models.CharField(max_length=16, validators=[misc.validate.validate_tel])),
                ('email', models.CharField(max_length=32, validators=[misc.validate.validate_email])),
                ('state', models.IntegerField()),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('account_code', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'message_information',
                'managed': True,
            },
        ),
    ]
