# Generated by Django 2.1.3 on 2019-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBrokerInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('broker_code', models.CharField(blank=True, max_length=64, null=True)),
                ('broker_work', models.TextField(blank=True, null=True)),
                ('broker_tag', models.IntegerField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_broker_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCheckInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('step_code', models.IntegerField(blank=True, null=True)),
                ('substep_code', models.IntegerField(blank=True, null=True)),
                ('substep_serial', models.CharField(blank=True, max_length=64, null=True)),
                ('cstate', models.IntegerField(blank=True, null=True)),
                ('cmsg', models.TextField(blank=True, null=True)),
                ('checker', models.CharField(blank=True, max_length=32, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_check_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectExpertInfo',
            fields=[
                ('pserial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('expert_code', models.CharField(blank=True, max_length=64, null=True)),
                ('ex_work', models.TextField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_expert_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('pserial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_start_time', models.DateTimeField(blank=True, null=True)),
                ('project_from', models.IntegerField(blank=True, null=True)),
                ('from_code', models.CharField(blank=True, max_length=64, null=True)),
                ('project_state', models.IntegerField(blank=True, null=True)),
                ('project_sub_state', models.IntegerField(blank=True, null=True)),
                ('last_time', models.DateTimeField(blank=True, null=True)),
                ('project_desc', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRrInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('rr_type', models.IntegerField(blank=True, null=True)),
                ('rr_main', models.IntegerField(blank=True, null=True)),
                ('rr_code', models.CharField(blank=True, max_length=64, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
                ('rr_work', models.TextField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_rr_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStepInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('step_code', models.IntegerField(blank=True, null=True)),
                ('btime', models.DateTimeField(blank=True, null=True)),
                ('etime', models.DateTimeField(blank=True, null=True)),
                ('step_state', models.IntegerField(blank=True, null=True)),
                ('step_msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_step_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSubstepDetailInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('step_code', models.IntegerField(blank=True, null=True)),
                ('substep_code', models.IntegerField(blank=True, null=True)),
                ('substep_serial', models.CharField(blank=True, max_length=64, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('submit_user', models.CharField(blank=True, max_length=64, null=True)),
                ('substep_serial_type', models.IntegerField(blank=True, null=True)),
                ('substep_serial_state', models.IntegerField(blank=True, null=True)),
                ('step_msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_substep_detail_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSubstepFileInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('step_code', models.IntegerField(blank=True, null=True)),
                ('substep_code', models.IntegerField(blank=True, null=True)),
                ('substep_serial', models.CharField(blank=True, max_length=64, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('file_caption', models.CharField(blank=True, max_length=64, null=True)),
                ('file_desp', models.CharField(blank=True, max_length=255, null=True)),
                ('file_typecode', models.CharField(blank=True, max_length=64, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('fileformat', models.IntegerField(blank=True, null=True)),
                ('up_perial', models.IntegerField(blank=True, null=True)),
                ('showtag', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('uper', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'project_substep_file_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSubstepInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('step_code', models.IntegerField(blank=True, null=True)),
                ('substep_code', models.IntegerField(blank=True, null=True)),
                ('btime', models.DateTimeField(blank=True, null=True)),
                ('etime', models.DateTimeField(blank=True, null=True)),
                ('substep_state', models.IntegerField(blank=True, null=True)),
                ('step_msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_substep_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSubstepSerialInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('step_code', models.IntegerField(blank=True, null=True)),
                ('substep_code', models.IntegerField(blank=True, null=True)),
                ('substep_serial', models.CharField(blank=True, max_length=64, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('substep_serial_type', models.IntegerField(blank=True, null=True)),
                ('substep_serial_state', models.IntegerField(blank=True, null=True)),
                ('step_msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_substep_serial_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamInfo',
            fields=[
                ('p_serial', models.AutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True)),
                ('team_code', models.CharField(blank=True, max_length=64, null=True)),
                ('broker_work', models.TextField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_team_info',
                'managed': False,
            },
        ),
    ]
