# Generated by Django 2.1.1 on 2019-03-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCheckInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('rm_code', models.CharField(blank=True, max_length=32, null=True)),
                ('match_pmemo', models.TextField(blank=True, null=True)),
                ('match_pmody', models.TextField(blank=True, null=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
                ('check_state', models.IntegerField(blank=True, null=True)),
                ('check_memo', models.TextField(blank=True, null=True)),
                ('checker', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'match_check_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqMatchBrokerInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('rm_code', models.CharField(blank=True, max_length=32, null=True)),
                ('broker', models.CharField(blank=True, max_length=64, null=True)),
                ('leader_tag', models.IntegerField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'req_match_broker_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqMatchInfo',
            fields=[
                ('rm_serial', models.AutoField(primary_key=True, serialize=False)),
                ('rm_code', models.CharField(blank=True, max_length=32, null=True)),
                ('rm_title', models.CharField(blank=True, max_length=64, null=True)),
                ('rm_object_type', models.IntegerField(blank=True, null=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True)),
                ('rm_abstract', models.TextField(blank=True, null=True)),
                ('rm_body', models.TextField(blank=True, null=True)),
                ('rm_type', models.IntegerField(blank=True, null=True)),
                ('rm_time', models.DateTimeField(blank=True, null=True)),
                ('rm_state', models.IntegerField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'req_match_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqMatchRrInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('rm_code', models.CharField(blank=True, max_length=32, null=True)),
                ('r_type', models.IntegerField(blank=True, null=True)),
                ('object_code', models.CharField(blank=True, max_length=64, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'req_match_rrinfo',
                'managed': False,
            },
        ),
    ]
