# Generated by Django 2.1.1 on 2019-12-12 11:05

from django.db import migrations, models
import misc.misc
import misc.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_code', models.CharField(default=True, max_length=64, null=True)),
                ('ccode', models.CharField(default=True, max_length=64, null=True)),
                ('rr_code', models.CharField(default=True, max_length=64, null=True)),
                ('type', models.IntegerField()),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agreement_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentFileinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('ecode', models.CharField(blank=True, max_length=64, null=True)),
                ('tcode', models.CharField(blank=True, max_length=8, null=True)),
                ('file_format', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=64, null=True)),
                ('add_id', models.CharField(blank=True, max_length=64, null=True)),
                ('file_order', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('operation_state', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_caption', models.CharField(blank=True, max_length=64, null=True)),
                ('publish', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attachment_fileinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentFileType',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('tcode', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('tname', models.CharField(blank=True, max_length=32, null=True)),
                ('tmemo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'attachment_file_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('object_code', models.CharField(blank=True, max_length=64, null=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True)),
                ('insert_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interest_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('mtype', models.IntegerField(default=2)),
                ('mcode', models.CharField(default=misc.misc.gen_uuid32, max_length=32, unique=True, verbose_name='类型代码')),
                ('pmcode', models.CharField(blank=True, default=-1, max_length=32, null=True, verbose_name='上级类型')),
                ('mname', models.CharField(blank=True, max_length=64, null=True, verbose_name='类型简称')),
                ('mabbr', models.CharField(blank=True, max_length=32, null=True, verbose_name='类型简称')),
                ('mlevel', models.IntegerField(blank=True, null=True, verbose_name='类型级别')),
                ('state', models.IntegerField(blank=True, default=1, verbose_name='状态')),
                ('is_hot', models.IntegerField(blank=True, default=0, verbose_name='是否热门(首页置顶)')),
                ('creater', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建者')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'major_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorUserinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('mtype', models.IntegerField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('user_code', models.CharField(blank=True, max_length=64, null=True)),
                ('mcode', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'major_userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('message_title', models.CharField(blank=True, max_length=64, null=True)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('account_code', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.IntegerField(default=0)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=32, null=True)),
                ('sms', models.IntegerField(blank=True, null=True)),
                ('sms_state', models.IntegerField(blank=True, null=True)),
                ('sms_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.IntegerField(blank=True, null=True)),
                ('email_state', models.IntegerField(blank=True, null=True)),
                ('email_account', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseBaseinfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('ecode', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('ename', models.CharField(blank=True, max_length=64, null=True)),
                ('eabbr', models.CharField(blank=True, max_length=32, null=True)),
                ('business_license', models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[misc.validate.validate_license])),
                ('eabstract', models.TextField(blank=True, null=True)),
                ('eabstract_detail', models.TextField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, max_length=128, null=True)),
                ('etel', models.CharField(blank=True, max_length=16, null=True, validators=[misc.validate.validate_tel])),
                ('manager', models.CharField(blank=True, max_length=16, null=True)),
                ('emobile', models.CharField(blank=True, max_length=16, null=True, validators=[misc.validate.validate_mobile])),
                ('eemail', models.CharField(blank=True, max_length=16, null=True, validators=[misc.validate.validate_email])),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True, validators=[misc.validate.validate_zipcode])),
                ('elevel', models.IntegerField(default=1)),
                ('credi_tvalue', models.IntegerField(default=0)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('manager_idtype', models.IntegerField(default=1)),
                ('manager_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'enterprise_baseinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdentityAuthorizationInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=64)),
                ('identity_code', models.CharField(max_length=64)),
                ('iab_time', models.DateTimeField(blank=True, null=True)),
                ('iae_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(default=1)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'identity_authorization_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdentityInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('identity_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('identity_name', models.CharField(max_length=64, unique=True)),
                ('identity_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(default=1)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ParamInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('param_code', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('pparam_code', models.CharField(default=0, max_length=64)),
                ('param_name', models.CharField(max_length=64, unique=True, verbose_name='参数名称')),
                ('param_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('param_value', models.TextField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'param_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(default=misc.misc.gen_uuid32, max_length=64, unique=True)),
                ('pname', models.CharField(blank=True, max_length=64, null=True)),
                ('psex', models.IntegerField(default=0)),
                ('pid_type', models.IntegerField(default=1)),
                ('pid', models.CharField(max_length=32)),
                ('pmobile', models.CharField(blank=True, max_length=16, null=True, validators=[misc.validate.validate_mobile])),
                ('ptel', models.CharField(blank=True, max_length=16, null=True, validators=[misc.validate.validate_tel])),
                ('pemail', models.CharField(blank=True, max_length=64, null=True, validators=[misc.validate.validate_email])),
                ('peducation', models.CharField(default=None, max_length=8)),
                ('pabstract', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(default=2)),
                ('creater', models.CharField(blank=True, max_length=32, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('account_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'personal_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Systematic_info',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('group', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('state', models.IntegerField(default=1)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'systematic_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemDistrict',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(default=0)),
                ('district_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('level', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(default='0000-00-00 00:00:00')),
            ],
            options={
                'db_table': 'system_district',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='personalinfo',
            unique_together={('pid_type', 'pid')},
        ),
        migrations.AlterUniqueTogether(
            name='identityauthorizationinfo',
            unique_together={('account_code', 'identity_code')},
        ),
    ]
